spring:
  application:    name: microservice-users
  datasource:    url: jdbc:postgresql://localhost:5432/db_microservices_users
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
    properties:      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    
logging:
  level:
    org:
      hibernate:
        SQL: debug
        
server:  port: ${PORT:0}
  
eureka:  instance:    instance-id: ${spring.application.name}:${random.value}
  client:    service-url:      defaultZone: http://localhost:8761/eureka
    