spring:
  application:
    name: microservice-answers
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_microservices_answers
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    
logging:
  level:
    org:
      hibernate:
        SQL: debug
        
server:
  port: ${PORT:0}
  
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    

