spring:
  application:
    name: microservice-zuul
    
server:  port: 8090
  
eureka:  client:    service-url:      defaultZone: http://localhost:8761/eureka
      
zuul:  routes:    users:
      service-id: microservice-users
      path: /api/users/**
    courses:
      service-id: microservice-courses
      path: /api/courses/**
    exams:
      service-id: microservice-exams
      path: /api/exams/**
    answers:
      service-id: microservice-answers
      path: /api/answers/**