spring:
  application:
    name: microservice-gateway
  cloud:
    gateway:
      routes:
      - id: microservice-users
        uri: lb://microservice-users
        predicates:
        - Path=/api/users/**
        filters:
        - StripPrefix=2
      - id: microservice-courses
        uri: lb://microservice-courses
        predicates:
        - Path=/api/courses/**
        filters:
        - StripPrefix=2
      - id: microservice-exams
        uri: lb://microservice-exams
        predicates:
        - Path=/api/exams/**
        filters:
        - StripPrefix=2
      - id: microservice-answers
        uri: lb://microservice-answers
        predicates:
        - Path=/api/answers/**
        filters:
        - StripPrefix=2
    #Deshabilitar ribbon para habilitar el balanceador de load balance de(Cloud LoadBalancer)
    loadbalancer:
      ribbon:
        enabled: false
      
server:
  port: 8090
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

